# Generated by Django 3.0.2 on 2020-03-14 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0002_auto_20200313_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObjectViewed',
        ),
    ]
