# Generated by Django 3.0.2 on 2020-02-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellyoshit', '0002_auto_20200218_1418'),
       # ('sellyoshit', '0002_auto_20200218_1110'),
        ('sellyoshit', '0002_auto_20200213_1541'),
        ('sellyoshit', '0002_auto_20200221_1458'),
    ]

    operations = [
    ]
