# Generated by Django 3.0.2 on 2020-02-24 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellyoshit', '0003_merge_20200224_1526'),
        ('sellyoshit', '0003_merge_20200224_1519'),
    ]

    operations = [
    ]
