# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: python:3.7

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - postgres:latest

variables:
  POSTGRES_DB: ci

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - ~/.cache/pip/

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  - python -V  # Print out python version
  - pip install -r requirements.txt

# In script, add the terminal command to test the directory you want; - python src/manage.py test <directory>
# It will then be tested as a part of CI Pipeline.
# DO NOT DELETE THE DATABASE called test_siverhog_sellyoshit! Use --keepdb behind tests that need to use the test db.
test:
  variables:
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
  script:
    - python src/manage.py test ads --keepdb
    - python src/manage.py test sellyoshit --keepdb
    - python src/manage.py test login --keepdb
