# Generated by Django 3.0.2 on 2020-03-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('messageid', models.AutoField(db_column='messageID', primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('sent', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('threadid', models.AutoField(db_column='threadID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'thread',
                'managed': False,
            },
        ),
    ]
