# Generated by Django 3.0.2 on 2020-02-24 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(default='Product')),
                ('product_description', models.TextField(default='There is no description available for this product.')),
                ('price', models.IntegerField(default=0)),
                ('seller', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('sold', models.BooleanField(default=False)),
                ('header_picture', models.ImageField(default='ads/default.png', upload_to='ads/users/')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
