# Generated by Django 3.0.2 on 2020-02-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('text', models.TextField(default='')),
                ('pris', models.CharField(default='', max_length=200)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(default=None, upload_to='images/')),
            ],
        ),
    ]
